# Source groups shared across several dev tools / specs, listed once
# instead of being copy-pasted into every target.
set(_miacode_chart_core
    src/core/chart/document/SimaiDocument.h
    src/core/chart/document/SimaiDocument.cpp
    src/core/chart/document/SimaiTimingMetadata.h
    src/core/chart/document/SimaiTimingMetadata.cpp
    src/core/chart/parser/SimaiParser.h
    src/core/chart/parser/SimaiParser.cpp
)
set(_miacode_log_core
    src/common/OperationLog.h
    src/common/OperationLog.cpp
    src/common/DebugLog.h
    src/common/DebugLog.cpp
)
set(_miacode_muri_analysis_core
    src/core/analysis/MuriTypes.h
    src/core/analysis/MuriTypes.cpp
    src/core/analysis/MuriAnalyzer.h
    src/core/analysis/MuriAnalyzer.cpp
    src/core/analysis/MuriAnalyzerGeometry.h
    src/core/analysis/MuriAnalyzerGeometry.cpp
    src/core/analysis/MuriAnalyzerModel.h
    src/core/analysis/MuriSlideReferenceData.h
    src/core/analysis/MuriSlideReferenceData.cpp
    src/core/analysis/MuriAnalyzerInternal.h
    src/core/analysis/MuriDiagnosticCollector.h
    src/core/analysis/MuriDiagnosticCollector.cpp
    src/core/analysis/MuriDiagnosticLabels.h
    src/core/analysis/MuriDiagnosticLabels.cpp
    src/core/analysis/MuriRuntimeModelBuilder.h
    src/core/analysis/MuriRuntimeModelBuilder.cpp
    src/core/analysis/MuriOverlayBuilder.h
    src/core/analysis/MuriOverlayBuilder.cpp
    src/core/analysis/MuriSlideWifiJudge.h
    src/core/analysis/MuriSlideWifiJudge.cpp
    src/core/analysis/MuriSimpleNoteJudge.h
    src/core/analysis/MuriSimpleNoteJudge.cpp
    src/core/analysis/MuriStaticChecker.h
    src/core/analysis/MuriStaticChecker.cpp
)
