# Helpers for the layered MiaCode libraries declared in cmake/MiaCodeModules.cmake.
include_guard(GLOBAL)

# miacode_add_module(<name>
#     SOURCES <files...>
#     [PUBLIC <deps...>] [PRIVATE <deps...>]
#     [QRC <resources/*.qrc...>])
# Static library exporting the src root. PUBLIC/PRIVATE take CMake targets and
# link items; scripts/governance/module_layering.py checks the miacode_* ones
# against the layering table.
function(miacode_add_module NAME)
    cmake_parse_arguments(PARSE_ARGV 1 MOD "" "" "SOURCES;PUBLIC;PRIVATE;QRC")
    if(MOD_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "miacode_add_module(${NAME}): unknown arguments ${MOD_UNPARSED_ARGUMENTS}")
    endif()
    qt_add_library(${NAME} STATIC ${MOD_SOURCES})
    target_include_directories(${NAME} PUBLIC "${PROJECT_SOURCE_DIR}/src")
    target_link_libraries(${NAME} PUBLIC ${MOD_PUBLIC} PRIVATE ${MOD_PRIVATE})
    if(MSVC)
        target_compile_options(${NAME} PRIVATE /FS)
    endif()
    foreach(qrc IN LISTS MOD_QRC)
        miacode_add_qrc(${NAME} "${qrc}")
    endforeach()
endfunction()

# miacode_add_qrc(<target> <file.qrc>)
# Registers a .qrc through the target-based qt_add_resources so static
# libraries initialize their resources without Q_INIT_RESOURCE: Qt links the
# generated initializer objects into every executable that consumes <target>.
# Resource paths (prefix + alias) are taken from the .qrc unchanged.
function(miacode_add_qrc TARGET QRC)
    get_filename_component(qrc_path "${QRC}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
    get_filename_component(qrc_dir "${qrc_path}" DIRECTORY)
    get_filename_component(qrc_name "${qrc_path}" NAME_WE)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${qrc_path}")
    file(READ "${qrc_path}" content)
    # Drop XML comments.
    while(TRUE)
        string(FIND "${content}" "<!--" comment_begin)
        if(comment_begin EQUAL -1)
            break()
        endif()
        string(FIND "${content}" "-->" comment_end)
        if(comment_end LESS comment_begin)
            message(FATAL_ERROR "${QRC}: unterminated XML comment")
        endif()
        math(EXPR comment_end "${comment_end} + 3")
        string(SUBSTRING "${content}" 0 ${comment_begin} head)
        string(SUBSTRING "${content}" ${comment_end} -1 tail)
        set(content "${head}${tail}")
    endwhile()
    string(REGEX MATCHALL "<qresource[^>]*>[^<]*(<file[^>]*>[^<]*</file>[^<]*)*</qresource>" blocks "${content}")
    if(NOT blocks)
        message(FATAL_ERROR "${QRC}: no <qresource> block")
    endif()
    set(index 0)
    foreach(block IN LISTS blocks)
        set(prefix "/")
        if(block MATCHES "<qresource[^>]*prefix=\"([^\"]*)\"")
            set(prefix "${CMAKE_MATCH_1}")
        endif()
        string(REGEX MATCHALL "<file[^>]*>[^<]*</file>" entries "${block}")
        set(files)
        foreach(entry IN LISTS entries)
            if(NOT entry MATCHES "<file([^>]*)>([^<]*)</file>")
                message(FATAL_ERROR "${QRC}: cannot parse ${entry}")
            endif()
            set(attributes "${CMAKE_MATCH_1}")
            string(STRIP "${CMAKE_MATCH_2}" relative)
            get_filename_component(file_path "${relative}" ABSOLUTE BASE_DIR "${qrc_dir}")
            set(alias "${relative}")
            if(attributes MATCHES "alias=\"([^\"]*)\"")
                set(alias "${CMAKE_MATCH_1}")
            endif()
            set_source_files_properties("${file_path}" PROPERTIES QT_RESOURCE_ALIAS "${alias}")
            list(APPEND files "${file_path}")
        endforeach()
        set(resource_name "${qrc_name}")
        if(index GREATER 0)
            set(resource_name "${qrc_name}_${index}")
        endif()
        qt_add_resources(${TARGET} "${resource_name}" PREFIX "${prefix}" BASE "${qrc_dir}" FILES ${files})
        math(EXPR index "${index} + 1")
    endforeach()
endfunction()
